# This scripts modifies the input fasta header to use in MICCA 
# Input comes from the seqs.fna generated by splitlib script from Qiime 1.9 

from Bio import SeqIO

infilename="seqs.fna"
outfilename="modfied_seqs.fna"

with open(outfilename,'a') as ofh :
  for i in SeqIO.parse(infilename, 'fasta'):
     sp_i = i.description.split(' ')
     x= ">" + sp_i[1]+";sample="+sp_i[0].split('_')[0]+"\n"+i.seq+"\n"
     ofh.writelines(x)
